export interface City {
  id: number
  name: string
}

export async function getCities(): Promise<City[]> {
  await new Promise((resolve) => setTimeout(resolve, 300))

  return [
    { id: 1, name: 'Adana' },
    { id: 2, name: 'Adıyaman' },
    { id: 3, name: 'Afyonkarahisar' },
    { id: 4, name: 'Ağrı' },
    { id: 5, name: 'Aksaray' },
    { id: 6, name: 'Amasya' },
    { id: 7, name: 'Ankara' },
    { id: 8, name: 'Antalya' },
    { id: 9, name: 'Ardahan' },
    { id: 10, name: 'Artvin' },
    { id: 11, name: 'Aydın' },
    { id: 12, name: 'Balıkesir' },
    { id: 13, name: 'Bartın' },
    { id: 14, name: 'Batman' },
    { id: 15, name: 'Bayburt' },
    { id: 16, name: 'Bilecik' },
    { id: 17, name: 'Bingöl' },
    { id: 18, name: 'Bitlis' },
    { id: 19, name: 'Bolu' },
    { id: 20, name: 'Burdur' },
    { id: 21, name: 'Bursa' },
    { id: 22, name: 'Çanakkale' },
    { id: 23, name: 'Çankırı' },
    { id: 24, name: 'Çorum' },
    { id: 25, name: 'Denizli' },
    { id: 26, name: 'Diyarbakır' },
    { id: 27, name: 'Düzce' },
    { id: 28, name: 'Edirne' },
    { id: 29, name: 'Elazığ' },
    { id: 30, name: 'Erzincan' },
    { id: 31, name: 'Erzurum' },
    { id: 32, name: 'Eskişehir' },
    { id: 33, name: 'Gaziantep' },
    { id: 34, name: 'Giresun' },
    { id: 35, name: 'Gümüşhane' },
    { id: 36, name: 'Hakkari' },
    { id: 37, name: 'Hatay' },
    { id: 38, name: 'Isparta' },
    { id: 39, name: 'Mersin' },
    { id: 40, name: 'İstanbul' },
    { id: 41, name: 'İzmir' },
    { id: 42, name: 'Kars' },
    { id: 43, name: 'Kastamonu' },
    { id: 44, name: 'Kayseri' },
    { id: 45, name: 'Kırıkkale' },
    { id: 46, name: 'Kırklareli' },
    { id: 47, name: 'Kilis' },
    { id: 48, name: 'Kütahya' },
    { id: 49, name: 'Malatya' },
    { id: 50, name: 'Manisa' },
    { id: 51, name: 'Kahramanmaraş' },
    { id: 52, name: 'Mardin' },
    { id: 53, name: 'Muğla' },
    { id: 54, name: 'Muş' },
    { id: 55, name: 'Nevşehir' },
    { id: 56, name: 'Niğde' },
    { id: 57, name: 'Ordu' },
    { id: 58, name: 'Osmaniye' },
    { id: 59, name: 'Rize' },
    { id: 60, name: 'Sakarya' },
    { id: 61, name: 'Samsun' },
    { id: 62, name: 'Şanlıurfa' },
    { id: 63, name: 'Şırnak' },
    { id: 64, name: 'Tekirdağ' },
    { id: 65, name: 'Tokat' },
    { id: 66, name: 'Trabzon' },
    { id: 67, name: 'Tunceli' },
    { id: 68, name: 'Uşak' },
    { id: 69, name: 'Van' },
    { id: 70, name: 'Yalova' },
    { id: 71, name: 'Zonguldak' },
  ]
}